from PyQt5 import QtCore, QtGui, QtWidgets
from telaDados import Ui_telaDados



class Ui_telaPrincipal(object):
    def setupUi(self, telaPrincipal):
        telaPrincipal.setObjectName("telaPrincipal")
        telaPrincipal.resize(900, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(telaPrincipal.sizePolicy().hasHeightForWidth())
        telaPrincipal.setSizePolicy(sizePolicy)
        telaPrincipal.setMinimumSize(QtCore.QSize(900, 550))
        telaPrincipal.setMaximumSize(QtCore.QSize(900, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/IMG-20250408-WA0038.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        telaPrincipal.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(telaPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(5, 85, 891, 101))
        self.frame.setStyleSheet("background-color: rgb(206, 206, 206);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.txt_crbio = QtWidgets.QLineEdit(self.frame)
        self.txt_crbio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_crbio.setObjectName("txt_crbio")
        self.horizontalLayout_3.addWidget(self.txt_crbio)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.txt_art_numero = QtWidgets.QLineEdit(self.frame)
        self.txt_art_numero.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_art_numero.setObjectName("txt_art_numero")
        self.horizontalLayout_3.addWidget(self.txt_art_numero)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7, 0, QtCore.Qt.AlignLeft)
        self.txt_data = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_data.sizePolicy().hasHeightForWidth())
        self.txt_data.setSizePolicy(sizePolicy)
        self.txt_data.setMaximumSize(QtCore.QSize(350, 20))
        self.txt_data.setSizeIncrement(QtCore.QSize(350, 20))
        self.txt_data.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_data.setObjectName("txt_data")
        self.horizontalLayout_4.addWidget(self.txt_data, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.campanha = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.campanha.sizePolicy().hasHeightForWidth())
        self.campanha.setSizePolicy(sizePolicy)
        self.campanha.setMinimumSize(QtCore.QSize(150, 20))
        self.campanha.setMaximumSize(QtCore.QSize(150, 20))
        self.campanha.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.campanha.setObjectName("campanha")
        self.horizontalLayout_4.addWidget(self.campanha)
        spacerItem1 = QtWidgets.QSpacerItem(230, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_9 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.txt_grupo = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_grupo.sizePolicy().hasHeightForWidth())
        self.txt_grupo.setSizePolicy(sizePolicy)
        self.txt_grupo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_grupo.setObjectName("txt_grupo")
        self.horizontalLayout_4.addWidget(self.txt_grupo)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 435, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(80, 80))
        self.label_5.setMaximumSize(QtCore.QSize(80, 80))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("icons/LogoPrincipal.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(5, 3, 891, 82))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButton_users = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_users.setMinimumSize(QtCore.QSize(80, 80))
        self.toolButton_users.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_users.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/iconClientes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_users.setIcon(icon1)
        self.toolButton_users.setIconSize(QtCore.QSize(80, 52))
        self.toolButton_users.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_users.setObjectName("toolButton_users")
        self.horizontalLayout_2.addWidget(self.toolButton_users)
        self.toolButton_table = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_table.setMinimumSize(QtCore.QSize(80, 80))
        self.toolButton_table.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_table.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/iconExcel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_table.setIcon(icon2)
        self.toolButton_table.setIconSize(QtCore.QSize(80, 52))
        self.toolButton_table.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_table.setObjectName("toolButton_table")
        self.horizontalLayout_2.addWidget(self.toolButton_table)
        self.toolButton_relatorio = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_relatorio.setMinimumSize(QtCore.QSize(80, 80))
        self.toolButton_relatorio.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_relatorio.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/iconPDF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_relatorio.setIcon(icon3)
        self.toolButton_relatorio.setIconSize(QtCore.QSize(80, 52))
        self.toolButton_relatorio.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_relatorio.setObjectName("toolButton_relatorio")
        self.horizontalLayout_2.addWidget(self.toolButton_relatorio)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.toolButton_sair = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_sair.setMinimumSize(QtCore.QSize(80, 80))
        self.toolButton_sair.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_sair.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/iconTrava.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_sair.setIcon(icon4)
        self.toolButton_sair.setIconSize(QtCore.QSize(80, 52))
        self.toolButton_sair.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_sair.setObjectName("toolButton_sair")
        self.horizontalLayout_2.addWidget(self.toolButton_sair)
        self.toolButton_sair_2 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_sair_2.setMinimumSize(QtCore.QSize(80, 80))
        self.toolButton_sair_2.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_sair_2.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/iconSair.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_sair_2.setIcon(icon5)
        self.toolButton_sair_2.setIconSize(QtCore.QSize(80, 52))
        self.toolButton_sair_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_sair_2.setObjectName("toolButton_sair_2")
        self.horizontalLayout_2.addWidget(self.toolButton_sair_2)
        telaPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(telaPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuMenu.setFont(font)
        self.menuMenu.setObjectName("menuMenu")
        self.menuRelatorio = QtWidgets.QMenu(self.menubar)
        self.menuRelatorio.setObjectName("menuRelatorio")
        telaPrincipal.setMenuBar(self.menubar)
        self.actionLogin = QtWidgets.QAction(telaPrincipal)
        self.actionLogin.setObjectName("actionLogin")
        self.actionSobre = QtWidgets.QAction(telaPrincipal)
        self.actionSobre.setObjectName("actionSobre")
        self.actionAjuda = QtWidgets.QAction(telaPrincipal)
        self.actionAjuda.setObjectName("actionAjuda")
        self.actionAtivacao = QtWidgets.QAction(telaPrincipal)
        self.actionAtivacao.setObjectName("actionAtivacao")
        self.actionRelatorio = QtWidgets.QAction(telaPrincipal)
        self.actionRelatorio.setObjectName("actionRelatorio")
        self.menuMenu.addAction(self.actionLogin)
        self.menuMenu.addAction(self.actionSobre)
        self.menuMenu.addAction(self.actionAjuda)
        self.menuMenu.addAction(self.actionAtivacao)
        self.menuRelatorio.addAction(self.actionRelatorio)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuRelatorio.menuAction())

        self.retranslateUi(telaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(telaPrincipal)

    def retranslateUi(self, telaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        telaPrincipal.setWindowTitle(_translate("telaPrincipal", "Sabia"))
        self.label_4.setText(_translate("telaPrincipal", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Empreedimento: PCH Serrinha ll </span><span style=\" font-size:11pt;\">| </span></p></body></html>"))
        self.label_2.setText(_translate("telaPrincipal", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Responsável Téc: Roberto Tomasi Jr. </span></p></body></html>"))
        self.label_3.setText(_translate("telaPrincipal", "<html><head/><body><p><span style=\" font-size:11pt;\">|</span><span style=\" font-size:11pt; font-weight:600;\"> CRBio n°:  </span><span style=\" font-size:11pt;\">|</span></p></body></html>"))
        self.label.setText(_translate("telaPrincipal", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">ART n°:</span></p></body></html>"))
        self.label_7.setText(_translate("telaPrincipal", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Data:</span></p></body></html>"))
        self.label_8.setText(_translate("telaPrincipal", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Campanha:   </span><span style=\" font-size:11pt;\">|</span></p></body></html>"))
        self.label_9.setText(_translate("telaPrincipal", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Grupo:</span></p></body></html>"))
        self.toolButton_users.setText(_translate("telaPrincipal", "Usuários"))
        self.toolButton_table.setText(_translate("telaPrincipal", "Tabela"))
        self.toolButton_relatorio.setText(_translate("telaPrincipal", "Andamentos"))
        self.toolButton_sair.setText(_translate("telaPrincipal", "Trava"))
        self.toolButton_sair_2.setText(_translate("telaPrincipal", "Sair"))
        self.menuMenu.setTitle(_translate("telaPrincipal", "Menu"))
        self.menuRelatorio.setTitle(_translate("telaPrincipal", "Relatorio"))
        self.actionLogin.setText(_translate("telaPrincipal", "Login"))
        self.actionSobre.setText(_translate("telaPrincipal", "Sobre"))
        self.actionAjuda.setText(_translate("telaPrincipal", "Ajuda"))
        self.actionAtivacao.setText(_translate("telaPrincipal", "Ativação"))
        self.actionRelatorio.setText(_translate("telaPrincipal", "Relatório"))
 
    # Conectando os botoes
        self.toolButton_relatorio.clicked.connect(self.telaDados)
    # Conectando a tela de dados
    def telaDados(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_telaDados()
        self.ui.setupUi(self.window)
        self.window.show()

    # # Conectando a tela login
    # def telaLogin(self):
    #     self.window = QtWidgets.QMainWindow()
    #     self.ui = Ui_MainWindow()
    #     self.ui.setupUi(self.window)
    #     self.window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    telaPrincipal = QtWidgets.QMainWindow()
    ui = Ui_telaPrincipal()
    ui.setupUi(telaPrincipal)
    telaPrincipal.show()
    sys.exit(app.exec_())
