from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_telaRelatorio(object):
    def setupUi(self, telaRelatorio):
        telaRelatorio.setObjectName("telaRelatorio")
        telaRelatorio.resize(1381, 1001)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(telaRelatorio.sizePolicy().hasHeightForWidth())
        telaRelatorio.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/LogoPrincipal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        telaRelatorio.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(telaRelatorio)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 90))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_20 = QtWidgets.QFrame(self.frame_2)
        self.frame_20.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_20.setStyleSheet("background-color: rgb(202, 202, 202);")
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_15 = QtWidgets.QFrame(self.frame_20)
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_titulo = QtWidgets.QLabel(self.frame_15)
        self.label_titulo.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.gridLayout_14.addWidget(self.label_titulo, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout_13.addWidget(self.frame_15, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_9.addWidget(self.frame_20)
        self.frame_18 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_18.sizePolicy().hasHeightForWidth())
        self.frame_18.setSizePolicy(sizePolicy)
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 90))
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_2.setContentsMargins(-1, -1, 9, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bt_sair = QtWidgets.QToolButton(self.frame_18)
        self.bt_sair.setMinimumSize(QtCore.QSize(80, 80))
        self.bt_sair.setMaximumSize(QtCore.QSize(80, 80))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/iconSair.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_sair.setIcon(icon1)
        self.bt_sair.setIconSize(QtCore.QSize(80, 52))
        self.bt_sair.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_sair.setObjectName("bt_sair")
        self.gridLayout_2.addWidget(self.bt_sair, 0, 2, 1, 1)
        self.bt_trava = QtWidgets.QToolButton(self.frame_18)
        self.bt_trava.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bt_trava.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/iconTrava.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_trava.setIcon(icon2)
        self.bt_trava.setIconSize(QtCore.QSize(80, 52))
        self.bt_trava.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_trava.setObjectName("bt_trava")
        self.gridLayout_2.addWidget(self.bt_trava, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(1200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_18)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 140, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setMinimumSize(QtCore.QSize(185, 100))
        self.frame_10.setMaximumSize(QtCore.QSize(100, 100))
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_nomeCientifico = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_nomeCientifico.setFont(font)
        self.label_nomeCientifico.setObjectName("label_nomeCientifico")
        self.verticalLayout_3.addWidget(self.label_nomeCientifico, 0, QtCore.Qt.AlignLeft)
        self.label_nomePopular = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_nomePopular.setFont(font)
        self.label_nomePopular.setObjectName("label_nomePopular")
        self.verticalLayout_3.addWidget(self.label_nomePopular, 0, QtCore.Qt.AlignLeft)
        self.label_nomeemIngles = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_nomeemIngles.setFont(font)
        self.label_nomeemIngles.setObjectName("label_nomeemIngles")
        self.verticalLayout_3.addWidget(self.label_nomeemIngles, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_15.addWidget(self.frame_10, 0, 0, 1, 1)
        self.frame_21 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy)
        self.frame_21.setMinimumSize(QtCore.QSize(197, 100))
        self.frame_21.setMaximumSize(QtCore.QSize(197, 100))
        self.frame_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txt_nomeCientifico = QtWidgets.QLineEdit(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_nomeCientifico.sizePolicy().hasHeightForWidth())
        self.txt_nomeCientifico.setSizePolicy(sizePolicy)
        self.txt_nomeCientifico.setMaximumSize(QtCore.QSize(145, 21))
        self.txt_nomeCientifico.setObjectName("txt_nomeCientifico")
        self.verticalLayout_2.addWidget(self.txt_nomeCientifico)
        self.txt_nomePopular = QtWidgets.QLineEdit(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_nomePopular.sizePolicy().hasHeightForWidth())
        self.txt_nomePopular.setSizePolicy(sizePolicy)
        self.txt_nomePopular.setMaximumSize(QtCore.QSize(145, 21))
        self.txt_nomePopular.setObjectName("txt_nomePopular")
        self.verticalLayout_2.addWidget(self.txt_nomePopular)
        self.txt_nomeEmingles = QtWidgets.QLineEdit(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_nomeEmingles.sizePolicy().hasHeightForWidth())
        self.txt_nomeEmingles.setSizePolicy(sizePolicy)
        self.txt_nomeEmingles.setMaximumSize(QtCore.QSize(145, 21))
        self.txt_nomeEmingles.setObjectName("txt_nomeEmingles")
        self.verticalLayout_2.addWidget(self.txt_nomeEmingles)
        self.gridLayout_15.addWidget(self.frame_21, 0, 1, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setMinimumSize(QtCore.QSize(185, 100))
        self.frame_11.setMaximumSize(QtCore.QSize(90, 100))
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_guildaTrofica = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_guildaTrofica.setFont(font)
        self.label_guildaTrofica.setObjectName("label_guildaTrofica")
        self.verticalLayout_4.addWidget(self.label_guildaTrofica, 0, QtCore.Qt.AlignLeft)
        self.label_statusdaConservacao = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_statusdaConservacao.setFont(font)
        self.label_statusdaConservacao.setObjectName("label_statusdaConservacao")
        self.verticalLayout_4.addWidget(self.label_statusdaConservacao, 0, QtCore.Qt.AlignLeft)
        self.label_7 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_15.addWidget(self.frame_11, 1, 0, 1, 1)
        self.frame_23 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_23.sizePolicy().hasHeightForWidth())
        self.frame_23.setSizePolicy(sizePolicy)
        self.frame_23.setMinimumSize(QtCore.QSize(197, 100))
        self.frame_23.setMaximumSize(QtCore.QSize(197, 100))
        self.frame_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.txt_guildaTrofica = QtWidgets.QLineEdit(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_guildaTrofica.sizePolicy().hasHeightForWidth())
        self.txt_guildaTrofica.setSizePolicy(sizePolicy)
        self.txt_guildaTrofica.setMinimumSize(QtCore.QSize(138, 0))
        self.txt_guildaTrofica.setMaximumSize(QtCore.QSize(146, 21))
        self.txt_guildaTrofica.setObjectName("txt_guildaTrofica")
        self.verticalLayout_5.addWidget(self.txt_guildaTrofica)
        self.txt_statusdaConservacao = QtWidgets.QLineEdit(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_statusdaConservacao.sizePolicy().hasHeightForWidth())
        self.txt_statusdaConservacao.setSizePolicy(sizePolicy)
        self.txt_statusdaConservacao.setMinimumSize(QtCore.QSize(145, 0))
        self.txt_statusdaConservacao.setMaximumSize(QtCore.QSize(140, 21))
        self.txt_statusdaConservacao.setObjectName("txt_statusdaConservacao")
        self.verticalLayout_5.addWidget(self.txt_statusdaConservacao)
        self.cb_tipodeRegistro = QtWidgets.QComboBox(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_tipodeRegistro.sizePolicy().hasHeightForWidth())
        self.cb_tipodeRegistro.setSizePolicy(sizePolicy)
        self.cb_tipodeRegistro.setMaximumSize(QtCore.QSize(145, 21))
        self.cb_tipodeRegistro.setObjectName("cb_tipodeRegistro")
        self.cb_tipodeRegistro.addItem("")
        self.cb_tipodeRegistro.setItemText(0, "")
        self.cb_tipodeRegistro.addItem("")
        self.cb_tipodeRegistro.addItem("")
        self.verticalLayout_5.addWidget(self.cb_tipodeRegistro)
        self.gridLayout_15.addWidget(self.frame_23, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_9)
        self.frame_16 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 6)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem2 = QtWidgets.QSpacerItem(20, 249, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem2, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_16)
        self.label_2.setMinimumSize(QtCore.QSize(80, 80))
        self.label_2.setMaximumSize(QtCore.QSize(80, 80))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icons/LogoPrincipal.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_12.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(386, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem3, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_16, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_10.addWidget(self.frame_5, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.frame_3)
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gb_Relatorio = QtWidgets.QGroupBox(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_Relatorio.sizePolicy().hasHeightForWidth())
        self.gb_Relatorio.setSizePolicy(sizePolicy)
        self.gb_Relatorio.setObjectName("gb_Relatorio")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gb_Relatorio)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_13 = QtWidgets.QFrame(self.gb_Relatorio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setMinimumSize(QtCore.QSize(380, 45))
        self.frame_13.setMaximumSize(QtCore.QSize(380, 45))
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setMinimumSize(QtCore.QSize(130, 34))
        self.frame_14.setMaximumSize(QtCore.QSize(130, 40))
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(119, 18))
        self.label_3.setMaximumSize(QtCore.QSize(85, 122))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setIndent(-1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_8.addWidget(self.frame_14, 0, 0, 1, 1)
        self.frame_17 = QtWidgets.QFrame(self.frame_13)
        self.frame_17.setMinimumSize(QtCore.QSize(215, 35))
        self.frame_17.setMaximumSize(QtCore.QSize(215, 35))
        self.frame_17.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_17.setFont(font)
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(190, 25))
        self.label.setMaximumSize(QtCore.QSize(193, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_17, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.frame_13, 0, 0, 1, 1)
        self.textEdit_blocodeNotas = QtWidgets.QTextEdit(self.gb_Relatorio)
        self.textEdit_blocodeNotas.setMinimumSize(QtCore.QSize(382, 375))
        self.textEdit_blocodeNotas.setMaximumSize(QtCore.QSize(390, 375))
        self.textEdit_blocodeNotas.setObjectName("textEdit_blocodeNotas")
        self.gridLayout_9.addWidget(self.textEdit_blocodeNotas, 1, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.gb_Relatorio)
        self.gridLayout_3.addWidget(self.frame_19, 0, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_22 = QtWidgets.QFrame(self.frame_8)
        self.frame_22.setMinimumSize(QtCore.QSize(457, 0))
        self.frame_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_24 = QtWidgets.QFrame(self.frame_22)
        self.frame_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_24)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 2, 2, 1, 1)
        self.bt_salvarTxt = QtWidgets.QPushButton(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_salvarTxt.sizePolicy().hasHeightForWidth())
        self.bt_salvarTxt.setSizePolicy(sizePolicy)
        self.bt_salvarTxt.setMinimumSize(QtCore.QSize(140, 25))
        self.bt_salvarTxt.setMaximumSize(QtCore.QSize(140, 25))
        self.bt_salvarTxt.setObjectName("bt_salvarTxt")
        self.gridLayout_7.addWidget(self.bt_salvarTxt, 3, 1, 1, 1)
        self.bt_salvarExcel = QtWidgets.QPushButton(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_salvarExcel.sizePolicy().hasHeightForWidth())
        self.bt_salvarExcel.setSizePolicy(sizePolicy)
        self.bt_salvarExcel.setMinimumSize(QtCore.QSize(140, 25))
        self.bt_salvarExcel.setMaximumSize(QtCore.QSize(130, 25))
        self.bt_salvarExcel.setObjectName("bt_salvarExcel")
        self.gridLayout_7.addWidget(self.bt_salvarExcel, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 370, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem5, 4, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem6, 0, 1, 1, 1)
        self.bt_salvarPdf = QtWidgets.QPushButton(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_salvarPdf.sizePolicy().hasHeightForWidth())
        self.bt_salvarPdf.setSizePolicy(sizePolicy)
        self.bt_salvarPdf.setMinimumSize(QtCore.QSize(140, 25))
        self.bt_salvarPdf.setMaximumSize(QtCore.QSize(140, 25))
        self.bt_salvarPdf.setObjectName("bt_salvarPdf")
        self.gridLayout_7.addWidget(self.bt_salvarPdf, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem7, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_24)
        self.verticalLayout_7.addWidget(self.frame_22)
        self.gridLayout_3.addWidget(self.frame_8, 0, 2, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setGeometry(QtCore.QRect(466, 0, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_9.addWidget(self.frame_3)
        self.gridLayout_16.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_25 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_25.sizePolicy().hasHeightForWidth())
        self.frame_25.setSizePolicy(sizePolicy)
        self.frame_25.setMinimumSize(QtCore.QSize(60, 0))
        self.frame_25.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_25.setStyleSheet("background-color: rgb(80, 80, 80);")
        self.frame_25.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.bt_salvar = QtWidgets.QToolButton(self.frame_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_salvar.sizePolicy().hasHeightForWidth())
        self.bt_salvar.setSizePolicy(sizePolicy)
        self.bt_salvar.setMinimumSize(QtCore.QSize(40, 36))
        self.bt_salvar.setMaximumSize(QtCore.QSize(46, 37))
        self.bt_salvar.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/iconSalvar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_salvar.setIcon(icon3)
        self.bt_salvar.setIconSize(QtCore.QSize(20, 20))
        self.bt_salvar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_salvar.setObjectName("bt_salvar")
        self.verticalLayout_8.addWidget(self.bt_salvar)
        self.bt_imprimir = QtWidgets.QToolButton(self.frame_25)
        self.bt_imprimir.setMinimumSize(QtCore.QSize(41, 36))
        self.bt_imprimir.setMaximumSize(QtCore.QSize(41, 36))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        self.bt_imprimir.setFont(font)
        self.bt_imprimir.setAcceptDrops(False)
        self.bt_imprimir.setToolTipDuration(-1)
        self.bt_imprimir.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/iconImprimir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_imprimir.setIcon(icon4)
        self.bt_imprimir.setIconSize(QtCore.QSize(20, 20))
        self.bt_imprimir.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_imprimir.setObjectName("bt_imprimir")
        self.verticalLayout_8.addWidget(self.bt_imprimir, 0, QtCore.Qt.AlignLeft)
        self.bt_galeria = QtWidgets.QToolButton(self.frame_25)
        self.bt_galeria.setMinimumSize(QtCore.QSize(41, 36))
        self.bt_galeria.setMaximumSize(QtCore.QSize(41, 36))
        self.bt_galeria.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/iconBeijaflor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_galeria.setIcon(icon5)
        self.bt_galeria.setIconSize(QtCore.QSize(20, 20))
        self.bt_galeria.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_galeria.setObjectName("bt_galeria")
        self.verticalLayout_8.addWidget(self.bt_galeria)
        self.bt_Aplicativos = QtWidgets.QToolButton(self.frame_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_Aplicativos.sizePolicy().hasHeightForWidth())
        self.bt_Aplicativos.setSizePolicy(sizePolicy)
        self.bt_Aplicativos.setMinimumSize(QtCore.QSize(41, 36))
        self.bt_Aplicativos.setMaximumSize(QtCore.QSize(41, 36))
        self.bt_Aplicativos.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/iconClientes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_Aplicativos.setIcon(icon6)
        self.bt_Aplicativos.setIconSize(QtCore.QSize(20, 20))
        self.bt_Aplicativos.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_Aplicativos.setObjectName("bt_Aplicativos")
        self.verticalLayout_8.addWidget(self.bt_Aplicativos)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem8)
        self.gridLayout_16.addWidget(self.frame_25, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        telaRelatorio.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(telaRelatorio)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1381, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuMenu = QtWidgets.QMenu(self.menuBar)
        self.menuMenu.setObjectName("menuMenu")
        telaRelatorio.setMenuBar(self.menuBar)
        self.actionCalcularMedia = QtWidgets.QAction(telaRelatorio)
        self.actionCalcularMedia.setObjectName("actionCalcularMedia")
        self.menuMenu.addAction(self.actionCalcularMedia)
        self.menuBar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(telaRelatorio)
        QtCore.QMetaObject.connectSlotsByName(telaRelatorio)

    def retranslateUi(self, telaRelatorio):
        _translate = QtCore.QCoreApplication.translate
        telaRelatorio.setWindowTitle(_translate("telaRelatorio", "Realatorio"))
        self.label_titulo.setText(_translate("telaRelatorio", "Relatório Levantamento de Aves: Dados Bióticos "))
        self.bt_sair.setText(_translate("telaRelatorio", "Sair"))
        self.bt_trava.setText(_translate("telaRelatorio", "Trava"))
        self.label_nomeCientifico.setText(_translate("telaRelatorio", "Nome Cientifico:"))
        self.label_nomePopular.setText(_translate("telaRelatorio", "Nome Popular:"))
        self.label_nomeemIngles.setText(_translate("telaRelatorio", "Nome em Inglês:"))
        self.label_guildaTrofica.setText(_translate("telaRelatorio", "Guilda Trófica:"))
        self.label_statusdaConservacao.setText(_translate("telaRelatorio", "Status de Preservação:"))
        self.label_7.setText(_translate("telaRelatorio", "Tipo de Registro:"))
        self.cb_tipodeRegistro.setItemText(1, _translate("telaRelatorio", "Vizualização"))
        self.cb_tipodeRegistro.setItemText(2, _translate("telaRelatorio", "Vocalização"))
        self.gb_Relatorio.setTitle(_translate("telaRelatorio", "Relatório:"))
        self.label_3.setText(_translate("telaRelatorio", "Observações"))
        self.label.setText(_translate("telaRelatorio", "Levantamento de aves:"))
        self.bt_salvarTxt.setText(_translate("telaRelatorio", "Salvar TXT"))
        self.bt_salvarExcel.setText(_translate("telaRelatorio", "Salvar EXCEL"))
        self.bt_salvarPdf.setText(_translate("telaRelatorio", "Salvar PDF"))
        self.bt_salvar.setText(_translate("telaRelatorio", "Salvar"))
        self.bt_imprimir.setText(_translate("telaRelatorio", "Imprimir"))
        self.bt_galeria.setText(_translate("telaRelatorio", "Galeria"))
        self.bt_Aplicativos.setText(_translate("telaRelatorio", "Apps"))
        self.menuMenu.setTitle(_translate("telaRelatorio", "Menu"))
        self.actionCalcularMedia.setText(_translate("telaRelatorio", "Calcular Média"))

        self.bt_sair.clicked.connect(telaRelatorio.close)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    telaRelatorio = QtWidgets.QMainWindow()
    ui = Ui_telaRelatorio()
    ui.setupUi(telaRelatorio)
    telaRelatorio.showFullScreen()
    sys.exit(app.exec_())
